package com.restaurant.inventory.prep;

import java.awt.image.BufferedImage;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import javax.imageio.ImageIO;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.http.*;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.test.context.ActiveProfiles;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test") @Import(StockApiTest.FixedTime.class)
class GuidanceMediaApiTest {
    @Autowired TestRestTemplate http;
    Object ingredient(){return http.postForEntity("/api/prep/ingredients",Map.of("name","Media "+UUID.randomUUID(),"unit","kg"),Map.class).getBody().get("id");}
    Object recipe(Object item,String name,String qty){return http.postForEntity("/api/prep/recipes",Map.of("name",name,"ingredients",List.of(Map.of("ingredientId",item,"quantity",qty,"unit","kg"))),Map.class).getBody().get("id");}
    Map<String,Object> draft(Object rid){return new LinkedHashMap<>(Map.ofEntries(Map.entry("recipeId",rid),Map.entry("title","Guide"),Map.entry("owner","Lead"),Map.entry("method","Prepare carefully"),Map.entry("handling","Keep covered"),Map.entry("substitutions","None"),Map.entry("portionNote","One portion"),Map.entry("applicability","Lunch"),Map.entry("nextAction","Check after service"),Map.entry("sourceReference","Card"),Map.entry("isDemo",false)));}
    byte[] image(int w,int h,boolean noisy,String format)throws Exception{var image=new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);var random=new Random(8);for(int y=0;y<h;y++)for(int x=0;x<w;x++)image.setRGB(x,y,noisy?random.nextInt(0x1000000):0x38a2ce);var out=new ByteArrayOutputStream();ImageIO.write(image,format,out);return out.toByteArray();}
    byte[] png(int w,int h,boolean noisy)throws Exception{return image(w,h,noisy,"png");}
    ResponseEntity<Map> upload(long doc,int version,byte[] bytes)throws Exception{return upload(doc,version,bytes,MediaType.IMAGE_PNG,"dish.png");}
    ResponseEntity<Map> upload(long doc,int version,byte[] bytes,MediaType type,String filename)throws Exception{return upload(doc,version,bytes,type,filename,"false","Cooking stage");}
    ResponseEntity<Map> upload(long doc,int version,byte[] bytes,MediaType type,String filename,String demo,String caption)throws Exception{var parts=new LinkedMultiValueMap<String,Object>();var resource=new ByteArrayResource(bytes){@Override public String getFilename(){return filename;}};var imageHeaders=new HttpHeaders();imageHeaders.setContentType(type);imageHeaders.setContentDispositionFormData("file",filename);parts.add("file",new HttpEntity<>(resource,imageHeaders));if(caption!=null)parts.add("caption",caption);parts.add("kind","PROCESS");parts.add("isDemo",demo);parts.add("expectedVersion",Integer.toString(version));var headers=new HttpHeaders();headers.setContentType(MediaType.MULTIPART_FORM_DATA);return http.exchange("/api/prep/guidance/"+doc+"/photos",HttpMethod.POST,new HttpEntity<>(parts,headers),Map.class);}
    int version(Map<?,?> d){return ((Number)d.get("draftVersion")).intValue();}
    @Test void uploadsPersistAndOnlyCurrentPublishedSnapshotCanServePhotos()throws Exception{
        Object item=ingredient(),rid=recipe(item,"Media dish","0.125");var doc=http.postForEntity("/api/prep/guidance",draft(rid),Map.class).getBody();long id=((Number)doc.get("id")).longValue();byte[] bytes=Files.readAllBytes(Path.of("../assets/demo-paneer-photo.png"));assertTrue(bytes.length>1024*1024);
        var uploaded=upload(id,1,bytes);assertEquals(HttpStatus.OK,uploaded.getStatusCode());var current=uploaded.getBody();assertEquals(2,version(current));var photos=(List<Map<String,Object>>)((Map<?,?>)current.get("draft")).get("photos");long photo=((Number)photos.getFirst().get("id")).longValue();assertEquals("/api/prep/guidance/"+id+"/photos/"+photo,photos.getFirst().get("url"));
        assertEquals(HttpStatus.OK,http.getForEntity("/api/prep/guidance/"+id+"/photos/"+photo,byte[].class).getStatusCode());var forbidden=http.getForEntity("/api/prep/guidance/photos/"+photo,byte[].class);assertEquals(HttpStatus.NOT_FOUND,forbidden.getStatusCode());
        var reload=http.getForObject("/api/prep/guidance/"+id,Map.class);assertEquals(1,((List<?>)((Map<?,?>)reload.get("draft")).get("photos")).size());
        assertEquals(HttpStatus.OK,http.postForEntity("/api/prep/guidance/"+id+"/publish",Map.of("expectedVersion",2),Map.class).getStatusCode());var staff=http.getForEntity("/api/prep/guidance/photos/"+photo,byte[].class);assertEquals(HttpStatus.OK,staff.getStatusCode());assertEquals(MediaType.IMAGE_PNG,staff.getHeaders().getContentType());assertEquals("nosniff",staff.getHeaders().getFirst("X-Content-Type-Options"));assertArrayEquals(bytes,staff.getBody());
        var stale=upload(id,1,png(3,3,false));assertEquals(HttpStatus.CONFLICT,stale.getStatusCode());
        var removed=http.exchange("/api/prep/guidance/"+id+"/photos/"+photo+"?expectedVersion=2",HttpMethod.DELETE,null,Map.class);assertEquals(HttpStatus.NO_CONTENT,removed.getStatusCode());assertEquals(HttpStatus.OK,http.getForEntity("/api/prep/guidance/"+id+"/photos/"+photo,byte[].class).getStatusCode());assertEquals(HttpStatus.OK,http.getForEntity("/api/prep/guidance/photos/"+photo,byte[].class).getStatusCode());
        var jpegDoc=http.postForEntity("/api/prep/guidance",draft(rid),Map.class).getBody();var jpeg=upload(((Number)jpegDoc.get("id")).longValue(),1,image(8,8,false,"jpg"),MediaType.IMAGE_JPEG,"dish.jpg");assertEquals(HttpStatus.OK,jpeg.getStatusCode());
    }
    @Test void invalidMediaVariantsLeaveDraftUnchanged()throws Exception{
        Object item=ingredient(),rid=recipe(item,"Invalid media dish","0.1");var doc=http.postForEntity("/api/prep/guidance",draft(rid),Map.class).getBody();long id=((Number)doc.get("id")).longValue();byte[] png=png(5,5,false);
        assertEquals(HttpStatus.BAD_REQUEST,upload(id,1,png,MediaType.IMAGE_JPEG,"spoof.jpg").getStatusCode());assertEquals(HttpStatus.BAD_REQUEST,upload(id,1,new byte[]{(byte)0x89,0x50,0x4e,0x47},MediaType.IMAGE_PNG,"broken.png").getStatusCode());assertEquals(HttpStatus.BAD_REQUEST,upload(id,1,new byte[0],MediaType.IMAGE_PNG,"empty.png").getStatusCode());assertEquals(HttpStatus.BAD_REQUEST,upload(id,1,png(6001,1,false),MediaType.IMAGE_PNG,"wide.png").getStatusCode());assertEquals(HttpStatus.PAYLOAD_TOO_LARGE,upload(id,1,new byte[5*1024*1024+1],MediaType.IMAGE_PNG,"large.png").getStatusCode());assertEquals(HttpStatus.BAD_REQUEST,upload(id,1,png,MediaType.IMAGE_PNG,"bad-flag.png","maybe","Caption").getStatusCode());assertEquals(HttpStatus.BAD_REQUEST,upload(id,1,png,MediaType.IMAGE_PNG,"missing-caption.png","false",null).getStatusCode());var after=http.getForObject("/api/prep/guidance/"+id,Map.class);assertEquals(1,version(after));assertTrue(((List<?>)((Map<?,?>)after.get("draft")).get("photos")).isEmpty());
    }
    @Test void invalidImageLeavesVersionUnchangedAndRecipeChangesSuppressTextAndPhotoUntilReviewedRepublish()throws Exception{
        Object item=ingredient(),rid=recipe(item,"Changing dish","0.125");var doc=http.postForEntity("/api/prep/guidance",draft(rid),Map.class).getBody();long id=((Number)doc.get("id")).longValue();
        var invalid=upload(id,1,new byte[]{1,2,3,4});assertEquals(HttpStatus.BAD_REQUEST,invalid.getStatusCode());assertEquals(1,version(http.getForObject("/api/prep/guidance/"+id,Map.class)));
        var uploaded=upload(id,1,png(10,10,false)).getBody();long photo=((Number)((Map<?,?>)((List<?>)((Map<?,?>)uploaded.get("draft")).get("photos")).getFirst()).get("id")).longValue();assertEquals(HttpStatus.OK,http.postForEntity("/api/prep/guidance/"+id+"/publish",Map.of("expectedVersion",2),Map.class).getStatusCode());
        var plan=http.postForEntity("/api/prep/plans",Map.of("recipeId",rid,"date","2026-10-02","portions",3),Map.class).getBody();long planId=((Number)plan.get("id")).longValue();assertEquals(HttpStatus.OK,http.exchange("/api/prep/plans/"+planId,HttpMethod.PUT,new HttpEntity<>(Map.of("recipeId",rid,"date","2026-10-02","portions",90)),Map.class).getStatusCode());var stillApplicable=(Map<?,?>)((List<?>)http.getForObject("/api/prep/guidance/published?recipeId="+rid,List.class)).getFirst();assertEquals(false,stillApplicable.get("stale"));
        assertEquals(HttpStatus.OK,http.exchange("/api/prep/recipes/"+rid,HttpMethod.PUT,new HttpEntity<>(Map.of("name","Renamed dish","ingredients",List.of(Map.of("ingredientId",item,"quantity","0.250","unit","kg")))),Map.class).getStatusCode());
        var manager=http.getForObject("/api/prep/guidance/"+id,Map.class);assertEquals(true,manager.get("recipeChanged"));var pub=http.getForObject("/api/prep/guidance/published?recipeId="+rid,List.class);var stale=(Map<?,?>)pub.getFirst();assertEquals(true,stale.get("stale"));assertFalse(stale.containsKey("method"));assertFalse(stale.containsKey("photos"));assertEquals(HttpStatus.NOT_FOUND,http.getForEntity("/api/prep/guidance/photos/"+photo,byte[].class).getStatusCode());
        var today=(Map<?,?>)http.getForObject("/api/prep/today?date=2026-10-02",Map.class);var dish=(Map<?,?>)((List<?>)today.get("dishes")).stream().filter(x->Objects.equals(((Map<?,?>)x).get("recipeId").toString(),rid.toString())).findFirst().orElseThrow();assertTrue(((List<?>)dish.get("guidance")).getFirst() instanceof Map);assertTrue(((Map<?,?>)((List<?>)dish.get("guidance")).getFirst()).get("stale").equals(true));
        assertEquals(HttpStatus.CONFLICT,http.postForEntity("/api/prep/guidance/"+id+"/publish",Map.of("expectedVersion",2),Map.class).getStatusCode());var reviewed=draft(rid);reviewed.put("expectedVersion",2);assertEquals(HttpStatus.OK,http.exchange("/api/prep/guidance/"+id,HttpMethod.PUT,new HttpEntity<>(reviewed),Map.class).getStatusCode());assertEquals(HttpStatus.OK,http.postForEntity("/api/prep/guidance/"+id+"/publish",Map.of("expectedVersion",3),Map.class).getStatusCode());assertEquals(false,http.getForObject("/api/prep/guidance/"+id,Map.class).get("recipeChanged"));
    }
    @Test void escalationsAreLocalIdempotentAndResolvable(){Object item=ingredient(),rid=recipe(item,"Question dish","1");var body=new LinkedHashMap<String,Object>(Map.of("recipeId",rid,"date","2026-10-02","question","Can we use an alternative?","reportedBy","Cook A","requestKey",UUID.randomUUID().toString()));var first=http.postForEntity("/api/prep/escalations",body,Map.class);assertEquals(HttpStatus.CREATED,first.getStatusCode());assertEquals(first.getBody().get("id"),http.postForEntity("/api/prep/escalations",body,Map.class).getBody().get("id"));body.put("question","Different question");assertEquals(HttpStatus.CONFLICT,http.postForEntity("/api/prep/escalations",body,Map.class).getStatusCode());long id=((Number)first.getBody().get("id")).longValue();var resolved=http.exchange("/api/prep/escalations/"+id+"/resolve",HttpMethod.PUT,new HttpEntity<>(Map.of("resolutionNote","Use the reviewed tofu recipe after allergen check.")),Map.class);assertEquals("RESOLVED",resolved.getBody().get("status"));assertTrue(http.getForObject("/api/prep/escalations",List.class).size()>=1);}
    @Test void concurrentSameQuestionKeyNeverCreatesDuplicatesOrReturnsServerError()throws Exception{
        Object rid=recipe(ingredient(),"Concurrent question","1");var body=Map.of("recipeId",rid,"date","2026-10-03","question","Fictional question","reportedBy","Sample cook","requestKey",UUID.randomUUID().toString());
        try(var pool=java.util.concurrent.Executors.newFixedThreadPool(2)){
            var responses=pool.invokeAll(List.of(()->http.postForEntity("/api/prep/escalations",body,Map.class).getStatusCode(),()->http.postForEntity("/api/prep/escalations",body,Map.class).getStatusCode()));
            var statuses=responses.stream().map(x->{try{return x.get();}catch(Exception e){throw new RuntimeException(e);}}).toList();assertTrue(statuses.contains(HttpStatus.CREATED));assertTrue(statuses.stream().allMatch(s->s.equals(HttpStatus.CREATED)||s.equals(HttpStatus.CONFLICT)));
        }
        assertEquals(1,http.getForObject("/api/prep/escalations",List.class).stream().filter(x->Objects.equals(((Map<?,?>)x).get("requestKey"),body.get("requestKey"))).count());
    }
    @Test void archivedRecipeMakesPublishedTextAndPhotosUnavailable()throws Exception{
        Object rid=recipe(ingredient(),"Archive guidance","1");var doc=http.postForEntity("/api/prep/guidance",draft(rid),Map.class).getBody();long id=((Number)doc.get("id")).longValue();var uploaded=upload(id,1,png(4,4,false)).getBody();long photo=((Number)((Map<?,?>)((List<?>)((Map<?,?>)uploaded.get("draft")).get("photos")).getFirst()).get("id")).longValue();
        assertEquals(HttpStatus.OK,http.postForEntity("/api/prep/guidance/"+id+"/publish",Map.of("expectedVersion",2),Map.class).getStatusCode());http.delete("/api/prep/recipes/"+rid);
        var published=(Map<?,?>)http.getForObject("/api/prep/guidance/published?recipeId="+rid,List.class).getFirst();assertEquals(true,published.get("stale"));assertFalse(published.containsKey("method"));assertEquals(HttpStatus.NOT_FOUND,http.getForEntity("/api/prep/guidance/photos/"+photo,byte[].class).getStatusCode());
    }
    @Test void sampleResetCascadesMediaAndQuestionsAndPreservesUnregisteredRecords()throws Exception{
        var resetBody=Map.of("confirmation","RESET FICTIONAL KITCHEN","mode","explore");var reset=http.postForEntity("/api/prep/demo/reset",resetBody,Map.class);assertEquals(HttpStatus.OK,reset.getStatusCode());Object sample=((List<?>)reset.getBody().get("recipes")).getFirst(),other=recipe(ingredient(),"Preserved media","1");
        var ids=new ArrayList<Long>();var photos=new ArrayList<Long>();var questions=new ArrayList<Object>();for(Object rid:List.of(sample,other)){var doc=http.postForEntity("/api/prep/guidance",draft(rid),Map.class).getBody();long id=((Number)doc.get("id")).longValue();ids.add(id);var uploaded=upload(id,1,png(4,4,false)).getBody();photos.add(((Number)((Map<?,?>)((List<?>)((Map<?,?>)uploaded.get("draft")).get("photos")).getFirst()).get("id")).longValue());questions.add(http.postForEntity("/api/prep/escalations",Map.of("recipeId",rid,"date","2026-10-03","question","Fictional reset check","reportedBy","Sample cook","requestKey",UUID.randomUUID().toString()),Map.class).getBody().get("id"));}
        assertEquals(HttpStatus.OK,http.postForEntity("/api/prep/demo/reset",resetBody,Map.class).getStatusCode());assertEquals(HttpStatus.NOT_FOUND,http.getForEntity("/api/prep/guidance/"+ids.getFirst(),Map.class).getStatusCode());assertEquals(HttpStatus.NOT_FOUND,http.getForEntity("/api/prep/guidance/"+ids.getFirst()+"/photos/"+photos.getFirst(),byte[].class).getStatusCode());assertEquals(HttpStatus.OK,http.getForEntity("/api/prep/guidance/"+ids.get(1)+"/photos/"+photos.get(1),byte[].class).getStatusCode());var queue=http.getForObject("/api/prep/escalations",List.class);assertFalse(queue.stream().anyMatch(x->Objects.equals(((Map<?,?>)x).get("id"),questions.getFirst())));assertTrue(queue.stream().anyMatch(x->Objects.equals(((Map<?,?>)x).get("id"),questions.get(1))));
    }
}
