import { useCallback,useEffect,useState } from 'react'
import GuidancePhoto from './GuidancePhoto'
import { useLanguage } from './language'
import { filterRecipes, matchesRecipeName } from './recipeSearch'

const blank={title:'',owner:'',method:'',handling:'',substitutions:'',portionNote:'',applicability:'',nextAction:'',sourceReference:'',isDemo:true}
const contentKeys=['title','method','handling','substitutions','portionNote','applicability','nextAction']
const cleanFields=value=>Object.fromEntries(Object.keys(blank).map(k=>[k,k==='isDemo'?Boolean(value?.isDemo):value?.[k]||'']))
const cleanEnglish=value=>Object.fromEntries(contentKeys.map(k=>[k,value?.[k]||'']))
const hasEnglish=value=>contentKeys.some(k=>String(value?.[k]||'').trim())
const publishedLanguages=publication=>Array.isArray(publication?.availableLanguages)?publication.availableLanguages:Object.keys(publication?.languageContents||{}).filter(k=>['hi','en'].includes(k)).length?Object.keys(publication.languageContents).filter(k=>['hi','en'].includes(k)):['hi']
const normalizedSet=values=>[...values].sort().join(',')
export default function GuidanceManager({api,onBusyChange}){
 const {language,t}=useLanguage()
 const [docs,setDocs]=useState([]),[recipes,setRecipes]=useState([]),[queue,setQueue]=useState([]),[errors,setErrors]=useState({}),[loading,setLoading]=useState({}),[doc,setDoc]=useState(null),[fields,setFields]=useState(blank),[english,setEnglish]=useState(cleanEnglish()),[recipeId,setRecipeId]=useState(''),[recipeSearch,setRecipeSearch]=useState(''),[photo,setPhoto]=useState({file:null,caption:'',kind:'PROCESS',isDemo:true}),[resolution,setResolution]=useState({}),[resolving,setResolving]=useState({}),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[contentTab,setContentTab]=useState('hi'),[reviewed,setReviewed]=useState(['hi']),[clearEnglish,setClearEnglish]=useState(false),[view,setView]=useState('guides')
 useEffect(()=>{onBusyChange?.(busy)},[busy,onBusyChange]);useEffect(()=>()=>onBusyChange?.(false),[onBusyChange])
 const activeRecipes=recipes.filter(r=>r.active!==false)
 const loadOne=useCallback(async(which)=>{setLoading(x=>({...x,[which]:true}));setErrors(x=>({...x,[which]:''}));try{const val=await api.get(which==='docs'?'/guidance':which==='recipes'?'/recipes':'/escalations');if(which==='docs')setDocs(val);if(which==='recipes')setRecipes(val);if(which==='queue')setQueue(val)}catch(e){setErrors(x=>({...x,[which]:e.message}))}finally{setLoading(x=>({...x,[which]:false}))}},[api])
 useEffect(()=>{loadOne('docs');loadOne('recipes');loadOne('queue')},[loadOne])
 useEffect(()=>{if(!doc&&!recipeId&&activeRecipes[0])setRecipeId(String(activeRecipes[0].id))},[activeRecipes,doc,recipeId])
 const savedHi=doc?cleanFields(doc.draft):blank,savedEn=doc?cleanEnglish(doc.draft?.translations?.en):cleanEnglish()
 const dirty=JSON.stringify(cleanFields(fields))!==JSON.stringify(savedHi)||JSON.stringify(cleanEnglish(english))!==JSON.stringify(savedEn)||clearEnglish
 const activeDoc=Boolean(doc&&!loading.recipes&&!errors.recipes&&!activeRecipes.some(r=>String(r.id)===String(doc.recipeId))),selectedRecipe=activeRecipes.find(r=>String(r.id)===String(doc?.recipeId||recipeId))
 const published=doc?.published,actualPublishedLanguages=publishedLanguages(published)
 const previewContents=published?published.languageContents||{hi:{title:published.title,method:published.method,handling:published.handling,substitutions:published.substitutions,portionNote:published.portionNote,applicability:published.applicability,nextAction:published.nextAction}}:{}
 const alreadyPublishedSameVersion=Boolean(published&&Number(doc?.publishedVersion)===Number(doc?.draftVersion))
 const reviewSetChanged=alreadyPublishedSameVersion&&normalizedSet(reviewed)!==normalizedSet(actualPublishedLanguages)
 const langComplete=lang=>{const value=lang==='hi'?fields:english;return ['title','method','applicability','nextAction'].every(k=>String(value?.[k]||'').trim())&&Boolean(fields.owner.trim())}
 const incompleteReviewed=reviewed.filter(lang=>!langComplete(lang))
 function loadDraftState(d){const nextHi=cleanFields(d?.draft||blank),nextEn=cleanEnglish(d?.draft?.translations?.en);setFields(nextHi);setEnglish(nextEn);setClearEnglish(false);setReviewed(publishedLanguages(d?.published));setContentTab('hi')}
 function noticeMessage(key,values){setNotice({key,values})}
 function openQuestions(){setView('questions');loadOne('queue')}
 function startNew(){if(busy||dirty)return;setDoc(null);loadDraftState(null);setRecipeId(String(activeRecipes[0]?.id||''));setRecipeSearch('');setPhoto({file:null,caption:'',kind:'PROCESS',isDemo:true});setNotice('');setView('editor')}
 async function edit(id){try{setBusy(true);const d=await api.get(`/guidance/${id}`);setDoc(d);loadDraftState(d);setRecipeId(String(d.recipeId));setPhoto({file:null,caption:'',kind:'PROCESS',isDemo:true});setNotice('');setView('editor')}catch(e){setNotice({raw:e.message})}finally{setBusy(false)}}
 function savePayload(){const payload={...cleanFields(fields),recipeId:Number(doc?.recipeId||recipeId),...(doc?{expectedVersion:doc.draftVersion}:{})};if(clearEnglish)payload.translations={en:null};else if(hasEnglish(english)||doc?.draft?.translations?.en)payload.translations={en:cleanEnglish(english)};return payload}
 async function save(e){e?.preventDefault?.();const preservedReview=[...reviewed];setBusy(true);setNotice('');try{const payload=savePayload(),d=doc?await api.put(`/guidance/${doc.id}`,payload):await api.post('/guidance',payload);setDoc(d);loadDraftState(d);setReviewed(preservedReview);setRecipeId(String(d.recipeId));await loadOne('docs');noticeMessage('manager.draftSaved')}catch(err){noticeMessage('manager.saveFailed',{error:err.message})}finally{setBusy(false)}}
 async function publish(){setBusy(true);setNotice('');try{const d=await api.post(`/guidance/${doc.id}/publish`,{expectedVersion:doc.draftVersion,reviewedLanguages:reviewed});setDoc(d);loadDraftState(d);await loadOne('docs');noticeMessage('manager.published')}catch(e){noticeMessage('manager.publishFailed',{error:e.message})}finally{setBusy(false)}}
 async function upload(e){e.preventDefault();if(!photo.file)return;if(!['image/jpeg','image/png'].includes(photo.file.type)||photo.file.size>5*1024*1024){noticeMessage('manager.photoType');return}const body=new FormData();body.append('file',photo.file);body.append('caption',photo.caption);body.append('kind',photo.kind);body.append('isDemo',String(photo.isDemo));body.append('expectedVersion',String(doc.draftVersion));setBusy(true);setNotice('');try{const d=await api.upload(`/guidance/${doc.id}/photos`,body);setDoc(d);await loadOne('docs');setPhoto({...photo,file:null,caption:''});noticeMessage('manager.photoAdded')}catch(e){noticeMessage('manager.photoFailed',{error:e.message})}finally{setBusy(false)}}
 async function removePhoto(id){setBusy(true);try{await api.remove(`/guidance/${doc.id}/photos/${id}?expectedVersion=${doc.draftVersion}`);const d=await api.get(`/guidance/${doc.id}`);setDoc(d);await loadOne('docs')}catch(e){noticeMessage('manager.photoRemoved',{error:e.message})}finally{setBusy(false)}}
 async function resolve(id){if(!resolution[id]?.trim())return;setResolving(x=>({...x,[id]:true}));setBusy(true);try{await api.put(`/escalations/${id}/resolve`,{resolutionNote:resolution[id].trim()});setResolution(x=>({...x,[id]:''}));await loadOne('queue')}catch(e){noticeMessage('manager.resolved',{error:e.message})}finally{setResolving(x=>({...x,[id]:false}));setBusy(false)}}
 const field=(k,value,onChange,opts={})=><label key={k}>{opts.label||t(`field.${k}`)}<textarea required={opts.required||false} maxLength={k==='title'||k==='owner'?120:k==='sourceReference'?1000:k==='method'?8000:4000} rows={k==='method'?6:2} disabled={busy||activeDoc||opts.disabled} value={value||''} onChange={e=>onChange(e.target.value)}/></label>
 const sharedChange=(key,value)=>setFields(current=>({...current,[key]:value}))
 const languageFields=contentTab==='hi'?fields:english,changeLanguageField=(key,value)=>contentTab==='hi'?setFields(current=>({...current,[key]:value})):setEnglish(current=>({...current,[key]:value}))
 const eligible=reviewed.length>0&&!incompleteReviewed.length
 return <section><div className="section-heading"><div><p className="eyebrow">{t('manager.eyebrow')}</p><h1>{t('manager.title')}</h1><p>{t('manager.intro')}</p></div>{view==='editor'?<button className="text-button" disabled={busy} onClick={()=>setView('guides')}>{t('manager.back')}</button>:<button className="button secondary" disabled={busy||dirty} onClick={startNew}>{t('manager.new')}</button>}</div>
 {view==='editor'&&dirty&&<p className="alert" role="status">{t('manager.dirty')} <button className="text-button" disabled={busy} onClick={()=>{loadDraftState(doc);setNotice('')}}>{t('manager.discard')}</button></p>}
 <div className="full guidance-view-tabs" role="tablist" aria-label={t('manager.title')}><button type="button" role="tab" aria-selected={view==='guides'} disabled={busy} onClick={()=>setView('guides')}>{t('manager.guidesTab')}</button><button type="button" role="tab" aria-selected={view==='questions'} disabled={busy} onClick={openQuestions}>{t('manager.questionsTab')}</button></div><div className="two-column">{view==='guides'&&<div className="panel"><h2>{t('manager.drafts')}</h2>{loading.docs?<p>{t('manager.loading')}</p>:errors.docs?<Error text={errors.docs} retry={()=>loadOne('docs')} t={t}/>:docs.map(d=><div className="compact-row" key={d.id}><div><strong>{d.recipeName} · {d.draft.title}</strong><small>{t('manager.savedVersion',{draft:d.draftVersion,published:d.publishedVersion||'—'})}{d.recipeChanged||d.draftRecipeChanged?` · ${t('manager.reviewStale')}`:''}</small></div><button className="text-button" disabled={busy||dirty} onClick={()=>edit(d.id)}>{t('manager.open')}</button></div>)}{!docs.length&&!loading.docs&&!errors.docs&&<p>{t('manager.none')}</p>}{dirty&&<button className="button secondary" disabled={busy} onClick={()=>setView('editor')}>{t('manager.resume')}</button>}</div>}{view==='questions'&&<div className="panel"><h2>{t('manager.queue')}</h2><p className="muted">{t('manager.local')}</p>{loading.queue?<p>{t('manager.loading')}</p>:errors.queue?<Error text={errors.queue} retry={()=>loadOne('queue')} t={t}/>:queue.map(q=><article key={q.id} className="compact-row"><div><strong>{q.recipeName} · {q.date} · {q.status==='OPEN'?t('manager.statusOpen'):t('manager.statusResolved')}</strong><p>{q.question}</p><small>{q.reportedBy} · {q.createdAt}</small>{q.status==='OPEN'?<><label>{t('manager.escalation')}<textarea required maxLength="2000" disabled={busy||resolving[q.id]} value={resolution[q.id]||''} onChange={e=>setResolution(x=>({...x,[q.id]:e.target.value}))}/></label><button className="button secondary" disabled={busy||!resolution[q.id]?.trim()||resolving[q.id]} onClick={()=>resolve(q.id)}>{resolving[q.id]?t('manager.resolving'):t('manager.resolve')}</button></>:<p>{q.resolutionNote}</p>}</div></article>)}{!queue.length&&!loading.queue&&!errors.queue&&<p>{t('manager.noQuestions')}</p>}</div>}</div>
 {view==='editor'&&<form className="panel form-grid" onSubmit={save}><h2 className="full">{doc?`${t('manager.title')} · ${doc.recipeName}`:t('manager.title')}</h2>{loading.recipes?<p className="full">{t('manager.loading')}</p>:errors.recipes&&<div className="full" role="alert">{t('manager.error',{error:errors.recipes})}<button type="button" className="text-button" onClick={()=>loadOne('recipes')}>{t('manager.retry')}</button></div>}{!doc&&<label className="full">{t('manager.searchRecipe')}<input type="search" value={recipeSearch} onChange={e=>setRecipeSearch(e.target.value)} disabled={busy||!!errors.recipes} autoComplete="off"/></label>}<label className="full">{t('manager.recipe')}<select required value={String(doc?.recipeId||recipeId)} disabled={!!doc||busy||!!errors.recipes} onChange={e=>setRecipeId(e.target.value)}><option value="">{t('manager.chooseRecipe')}</option>{doc&&!activeRecipes.some(r=>String(r.id)===String(doc.recipeId))&&<option value={String(doc.recipeId)}>{doc.recipeName} · {t('manager.inactive')}</option>}{filterRecipes(activeRecipes,recipeSearch,doc?.recipeId||recipeId).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{!doc&&recipeSearch.trim()&&!activeRecipes.some(r=>matchesRecipeName(r,recipeSearch))&&<small className="muted" role="status">{t('manager.noRecipeMatch')}</small>}</label>{activeDoc&&<p className="full badge review">{t('manager.archived')}</p>}{selectedRecipe&&<details className="full guidance-optional"><summary>{t('manager.perServing')}</summary><div className="panel">{selectedRecipe.ingredients?.map(l=><p key={l.ingredientId||l.id}>{l.name}: {l.quantity} {l.unit}</p>)}</div></details>}
 <fieldset className="guidance-fields shared-guidance-fields"><legend>{t('manager.identity')}</legend>{field('title',fields.title,v=>sharedChange('title',v),{required:true,label:t('manager.titleField')})}{field('owner',fields.owner,v=>sharedChange('owner',v),{required:true})}<label><input type="checkbox" disabled={busy||activeDoc} checked={fields.isDemo} onChange={e=>sharedChange('isDemo',e.target.checked)}/>{t('manager.demo')}</label></fieldset>
 <div className="full guidance-language-tabs" role="tablist" aria-label={t('manager.contentLanguage')}><button type="button" role="tab" aria-selected={contentTab==='hi'} onClick={()=>setContentTab('hi')}>{t('manager.langHi')}</button><button type="button" role="tab" aria-selected={contentTab==='en'} onClick={()=>setContentTab('en')}>{t('manager.langEn')}</button></div>
 <fieldset className="guidance-fields essential-fields"><legend>{contentTab==='hi'?t('manager.langHi'):t('manager.langEn')}</legend>{contentTab==='en'&&field('title',english.title,v=>setEnglish(current=>({...current,title:v})),{label:t('manager.englishTitle')})}{['method','applicability','nextAction'].map(k=>field(k,languageFields[k],v=>changeLanguageField(k,v)))}</fieldset>{(hasEnglish(english)||doc?.draft?.translations?.en)&&<button type="button" className="text-button full" disabled={busy||activeDoc} onClick={()=>{setEnglish(cleanEnglish());setClearEnglish(true)}}>{t('manager.clearEnglish')}</button>}<details className="guidance-optional"><summary>{t('manager.optional')}</summary><fieldset className="guidance-fields"><legend>{t('manager.extra')}</legend>{['handling','substitutions','portionNote'].map(k=>field(k,languageFields[k],v=>changeLanguageField(k,v)))}{field('sourceReference',fields.sourceReference,v=>sharedChange('sourceReference',v))}</fieldset></details>
 <div className="full form-footer"><button className="button" disabled={busy||(!doc&&!recipeId)||activeDoc}>{t('manager.save')}</button><span className="muted">{doc?t('manager.savedVersion',{draft:doc.draftVersion,published:doc.publishedVersion||'—'}):t('manager.saveFirst')}</span></div></form>}
 {notice&&<p className="alert" role="status">{notice.raw||t(notice.key,notice.values)}</p>}
 {view==='editor'&&doc&&<><div className="panel"><h2>{t('manager.review')}</h2>{(doc.recipeChanged||doc.draftRecipeChanged)&&<p className="badge review">{t('manager.recipeChanged')}</p>}<p>{t('manager.reviewIntro')}</p><fieldset className="reviewed-language-set"><legend>{t('manager.review')}</legend>{['hi','en'].map(lang=><label key={lang}><input type="checkbox" disabled={busy||activeDoc} checked={reviewed.includes(lang)} onChange={e=>setReviewed(current=>e.target.checked?[...current,lang]:current.filter(x=>x!==lang))}/>{t(lang==='hi'?'manager.reviewHi':'manager.reviewEn')} {langComplete(lang)?'':' · '+t('manager.unavailable')}</label>)}</fieldset>{incompleteReviewed.length>0&&<p className="badge review">{t('manager.unavailable')}</p>}{reviewSetChanged&&<p className="badge review" role="alert">{t('manager.saveReview')} <button type="button" className="button secondary" disabled={busy||dirty||activeDoc} onClick={()=>save()}>{t('manager.save')}</button></p>}{published&&<details className="guidance-optional"><summary>{t('manager.historyDisclosure')}</summary><div><h3>{published.stale?t('manager.reviewStale'):t('manager.reviewCurrent')} · v{published.version}</h3><p>{published.title} · {published.owner} · {published.publishedAt}</p><p>{t('manager.historyLanguages',{languages:actualPublishedLanguages.map(x=>x==='hi'?t('manager.hi'):t('manager.en')).join(', ')})}</p>{published.stale&&<p>{t('manager.recipeChanged')}</p>}{actualPublishedLanguages.map(lang=>{const content=previewContents[lang]||{};return <article className="published-language-preview" key={lang} lang={lang}><h4>{lang==='hi'?t('manager.hi'):t('manager.en')}</h4>{content.title&&<p><strong>{lang==='hi'?t('manager.titleField'):t('manager.englishTitle')}:</strong> {content.title}</p>}{content.method&&<p className="note-text"><strong>{t('manager.method')}:</strong> {content.method}</p>}{content.handling&&<p><strong>{t('manager.handling')}:</strong> {content.handling}</p>}{content.substitutions&&<p><strong>{t('manager.substitutions')}:</strong> {content.substitutions}</p>}{content.portionNote&&<p><strong>{t('manager.portionNote')}:</strong> {content.portionNote}</p>}{content.applicability&&<p><strong>{t('manager.applicability')}:</strong> {content.applicability}</p>}{content.nextAction&&<p><strong>{t('manager.nextAction')}:</strong> {content.nextAction}</p>}</article>})}{published.photos?.map(p=><GuidancePhoto key={p.id} photo={{...p,url:`/api/prep/guidance/${doc.id}/photos/${p.id}`}}/>)}</div></details>}<button className="button" aria-label={t('manager.publish')} disabled={busy||dirty||activeDoc||!eligible||Boolean(doc.draftRecipeChanged)||reviewSetChanged} onClick={publish}>{t('manager.publish')}</button>{dirty&&<p className="muted">{t('manager.dirty')}</p>}</div>
 <details className="panel guidance-optional"><summary>{t('manager.photoDisclosure')}</summary><h2>{t('manager.photo')}</h2><p>{t('manager.photoRules')}</p>{doc.draft.photos?.map(p=><div key={p.id}><GuidancePhoto photo={p}/><button className="text-button" disabled={busy||dirty||activeDoc} onClick={()=>removePhoto(p.id)}>{t('manager.removePhoto')}</button></div>)}<form className="form-grid" onSubmit={upload}><label className="full">{t('manager.file')}<input required type="file" disabled={busy||dirty||activeDoc} accept="image/jpeg,image/png" onChange={e=>setPhoto({...photo,file:e.target.files?.[0]||null})}/></label><label>{t('manager.caption')}<input required maxLength="240" disabled={busy||dirty||activeDoc} value={photo.caption} onChange={e=>setPhoto({...photo,caption:e.target.value})}/></label><label>{t('manager.kind')}<select disabled={busy||dirty||activeDoc} value={photo.kind} onChange={e=>setPhoto({...photo,kind:e.target.value})}><option value="PROCESS">{t('manager.prep')}</option><option value="PORTION">{t('manager.portion')}</option></select></label><label><input type="checkbox" disabled={busy||dirty||activeDoc} checked={photo.isDemo} onChange={e=>setPhoto({...photo,isDemo:e.target.checked})}/>{t('manager.demo')}</label><button className="button secondary" disabled={busy||dirty||activeDoc||doc.draft.photos?.length>=6}>{t('manager.addPhoto')}</button>{dirty&&<p className="muted full">{t('manager.photoSave')}</p>}</form></details></>}
 </section>
}
function Error({text,retry,t}){return <div role="alert">{t('manager.error',{error:text})}<button className="text-button" onClick={retry}>{t('manager.retry')}</button></div>}
