import { useCallback,useEffect,useState } from 'react'
import { useLanguage } from './language'

const reasons={WASTE:['EXPIRED','SPOILED','DAMAGED','PREP_LOSS','OVERPRODUCTION','OTHER'],USAGE:['MEAL_PREPARATION'],COUNT_ADJUSTMENT:['COUNT_DISCREPANCY']}
const titleCase=value=>value.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase())
export default function NotesPanel({items,api,mutate,saving,reportError}) {
  const {t}=useLanguage(),[tab,setTab]=useState('waste'),[history,setHistory]=useState([]),[notes,setNotes]=useState([]),[recipes,setRecipes]=useState([]),[localBusy,setLocalBusy]=useState(false)
  const [removal,setRemoval]=useState({ingredientId:'',lotId:'',quantity:'',kind:'WASTE',reason:'SPOILED',note:''}),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID())
  const [note,setNote]=useState({targetType:'INGREDIENT',targetId:'',kind:'HANDLING',text:'',actor:'Anita Rao (sample manager)'})
  const load=useCallback(async()=>{const [h,n,r]=await Promise.all([api.get('/history'),api.get('/notes'),api.get('/recipes')]);setHistory(h);setNotes(n);setRecipes(r)},[api])
  useEffect(()=>{load().catch(reportError)},[load,items,reportError])
  const item=items.find(i=>String(i.id)===removal.ingredientId),lots=item?.lots.filter(l=>Number(l.remaining)>0)||[],workBusy=saving||localBusy
  async function remove(event){event.preventDefault();setLocalBusy(true);try{if(await mutate(()=>api.post('/removals',{...removal,unit:item.unit,requestKey}),{key:'support.removalSuccess'})){setRemoval(current=>({...current,quantity:'',note:''}));setRequestKey(crypto.randomUUID());try{await load()}catch(error){reportError(error)}}}finally{setLocalBusy(false)}}
  async function saveNote(event){event.preventDefault();setLocalBusy(true);try{if(await mutate(()=>note.id?api.put(`/notes/${note.id}`,note):api.post('/notes',note),{key:'support.noteSuccess'})){setNote(current=>({targetType:'INGREDIENT',targetId:'',kind:'HANDLING',text:'',actor:current.actor}));try{await load()}catch(error){reportError(error)}}}finally{setLocalBusy(false)}}
  const targets=note.targetType==='INGREDIENT'?items:recipes
  return <section><div className="section-heading"><div><p className="eyebrow">{t('support.recordsEyebrow')}</p><h1>{t('support.recordsTitle')}</h1><p>{t('support.recordsIntro')}</p></div></div>
    <div className="tabs" role="tablist"><button type="button" role="tab" disabled={workBusy} aria-selected={tab==='waste'} className={tab==='waste'?'active':''} onClick={()=>setTab('waste')}>{t('support.removals')}</button><button type="button" role="tab" disabled={workBusy} aria-selected={tab==='notes'} className={tab==='notes'?'active':''} onClick={()=>setTab('notes')}>{t('support.managerNotes')}</button><button type="button" role="tab" disabled={workBusy} aria-selected={tab==='history'} className={tab==='history'?'active':''} onClick={()=>setTab('history')}>{t('support.movementHistory')}</button></div>
    {tab==='waste'&&<form className="panel form-grid" onSubmit={remove}><fieldset disabled={workBusy} className="form-grid-lock"><h2 className="full">{t('support.removalTitle')}</h2><p className="muted full">{t('support.removalIntro')}</p><label>{t('support.removalIngredient')}<select required value={removal.ingredientId} onChange={e=>setRemoval({...removal,ingredientId:e.target.value,lotId:''})}><option value="">{t('support.chooseIngredient')}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>{t('support.selectedLot')}<select required value={removal.lotId} onChange={e=>setRemoval({...removal,lotId:e.target.value})}><option value="">{t('support.chooseLot')}</option>{lots.map(l=><option key={l.id} value={l.id}>Lot #{l.id} · {l.remaining} {l.unit} · {l.labelDate||t('support.unknown')}</option>)}</select></label><label>{t('support.removedQuantity',{unit:item?.unit||' stock unit'})}<input required type="number" min="0.000001" step="any" value={removal.quantity} onChange={e=>setRemoval({...removal,quantity:e.target.value})}/></label><label>{t('support.removalType')}<select value={removal.kind} onChange={e=>setRemoval({...removal,kind:e.target.value,reason:reasons[e.target.value][0]})}><option value="WASTE">{t('support.waste')}</option><option value="USAGE">{t('support.usage')}</option><option value="COUNT_ADJUSTMENT">{t('support.countAdjustment')}</option></select></label><label>{t('support.reason')}<select value={removal.reason} onChange={e=>setRemoval({...removal,reason:e.target.value})}>{reasons[removal.kind].map(r=><option value={r} key={r}>{t(`support.reason.${r}`)||titleCase(r)}</option>)}</select></label><label className="full">{t('support.removalNote')}<textarea rows="2" maxLength={2000} value={removal.note} onChange={e=>setRemoval({...removal,note:e.target.value})}/></label><div className="full form-footer"><button className="button" disabled={!lots.length}>{t('support.recordRemoval')}</button><span className="muted">{t('support.flagsDontRemove')}</span></div></fieldset></form>}
    {tab==='notes'&&<><form className="panel form-grid" onSubmit={saveNote}><fieldset disabled={workBusy} className="form-grid-lock"><h2 className="full">{t(note.id?'support.editNoteTitle':'support.noteTitle')}</h2><label>{t('support.noteApplies')}<select value={note.targetType} onChange={e=>setNote({...note,targetType:e.target.value,targetId:''})}><option value="INGREDIENT">{t('support.ingredient')}</option><option value="RECIPE">{t('support.dish')}</option></select></label><label>{t('support.target')}<select required value={note.targetId} onChange={e=>setNote({...note,targetId:e.target.value})}><option value="">{t('support.chooseIngredient')}</option>{targets.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>{t('support.noteKind')}<select value={note.kind} onChange={e=>setNote({...note,kind:e.target.value})}><option value="HANDLING">{t('support.handling')}</option><option value="APPROVED_SUBSTITUTION">{t('support.substitution')}</option></select></label><label>{t('support.author')}<input required maxLength={120} value={note.actor} onChange={e=>setNote({...note,actor:e.target.value})}/></label><label className="full">{t('support.guidanceText')}<textarea required rows="3" maxLength={4000} value={note.text} onChange={e=>setNote({...note,text:e.target.value})}/></label><div className="full"><button className="button" disabled={workBusy}>{t(note.id?'support.saveNoteChanges':'support.saveNote')}</button>{note.id&&<button type="button" className="text-button" onClick={()=>setNote({targetType:'INGREDIENT',targetId:'',kind:'HANDLING',text:'',actor:note.actor})}>{t('support.cancelEdit')}</button>}</div></fieldset></form>{notes.map(n=><article className="panel" key={n.id}><div className="section-title"><h2>{n.targetName}</h2><span className="badge">{t(`support.noteKind.${n.kind}`)}</span></div><p className="note-text">{n.text}</p><p className="muted small">{t('support.lastEdited',{actor:n.actor,date:n.updatedAt.replace('T',' ')})}</p><button className="text-button" disabled={workBusy} onClick={()=>{setNote({...n,targetId:String(n.targetId)});window.scrollTo({top:0,behavior:'smooth'})}}>{t('support.editNote',{name:n.targetName})}</button></article>)}{!notes.length&&<p className="panel muted">{t('support.noNotes')}</p>}</>}
    {tab==='history'&&<div className="panel"><h2>{t('support.historyTitle')}</h2><p className="muted">{t('support.historyIntro')}</p><div className="table-wrap"><table><thead><tr><th>{t('support.when')}</th><th>{t('support.ingredientLot')}</th><th>{t('support.type')}</th><th>{t('support.quantity')}</th><th>{t('support.reasonNote')}</th><th>{t('support.recordedBy')}</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{h.createdAt.replace('T',' ')}</td><td>{h.ingredient}<br/>Lot #{h.lotId}</td><td>{t(`support.kind.${h.kind}`)||titleCase(h.kind)}</td><td>{h.quantity} {h.unit}</td><td>{h.reason?t(`support.reason.${h.reason}`)||titleCase(h.reason):t('support.actualReceipt')}<div className="muted small">{h.note}</div></td><td>{h.actor}</td></tr>)}</tbody></table></div>{!history.length&&<p className="muted">{t('support.noMovements')}</p>}</div>}
  </section>
}
