import { useCallback,useEffect,useState } from 'react'

const reasons={WASTE:['EXPIRED','SPOILED','DAMAGED','PREP_LOSS','OVERPRODUCTION','OTHER'],USAGE:['MEAL_PREPARATION'],COUNT_ADJUSTMENT:['COUNT_DISCREPANCY']}
const label=value=>value.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase())
export default function NotesPanel({items,api,mutate,saving,reportError}) {
  const [tab,setTab]=useState('waste'),[history,setHistory]=useState([]),[notes,setNotes]=useState([]),[recipes,setRecipes]=useState([])
  const [removal,setRemoval]=useState({ingredientId:'',lotId:'',quantity:'',kind:'WASTE',reason:'SPOILED',note:''}),[requestKey,setRequestKey]=useState(()=>crypto.randomUUID())
  const [note,setNote]=useState({targetType:'INGREDIENT',targetId:'',kind:'HANDLING',text:'',actor:'Anita Rao (sample manager)'})
  const load=useCallback(async()=>{const [h,n,r]=await Promise.all([api.get('/history'),api.get('/notes'),api.get('/recipes')]);setHistory(h);setNotes(n);setRecipes(r)},[api])
  useEffect(()=>{load().catch(reportError)},[load,items,reportError])
  const item=items.find(i=>String(i.id)===removal.ingredientId),lots=item?.lots.filter(l=>Number(l.remaining)>0)||[]
  async function remove(event){event.preventDefault();if(await mutate(()=>api.post('/removals',{...removal,unit:item.unit,requestKey}),'Stock removal recorded once. The lot balance and estimate are updated.')){setRemoval({...removal,quantity:'',note:''});setRequestKey(crypto.randomUUID());await load()}}
  async function saveNote(event){event.preventDefault();if(await mutate(()=>note.id?api.put(`/notes/${note.id}`,note):api.post('/notes',note),'Manager note saved.')){setNote({targetType:'INGREDIENT',targetId:'',kind:'HANDLING',text:'',actor:note.actor});await load()}}
  const targets=note.targetType==='INGREDIENT'?items:recipes
  return <section><div className="section-heading"><div><p className="eyebrow">KNOW WHAT CHANGED</p><h1>Waste & notes</h1><p>Record losses with a reason. Keep your kitchen's guidance close.</p></div></div><div className="tabs"><button className={tab==='waste'?'active':''} onClick={()=>setTab('waste')}>Log stock removal</button><button className={tab==='notes'?'active':''} onClick={()=>setTab('notes')}>Manager notes</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>Movement history</button></div>
    {tab==='waste'&&<form className="panel form-grid" onSubmit={remove}><h2 className="full">What left the pantry?</h2><p className="muted full">Waste, ordinary meal usage, and count discrepancies are recorded separately. Select the lot you actually removed stock from.</p><label>Removal ingredient<select required value={removal.ingredientId} onChange={e=>setRemoval({...removal,ingredientId:e.target.value,lotId:''})}><option value="">Choose ingredient</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><label>Selected lot<select required value={removal.lotId} onChange={e=>setRemoval({...removal,lotId:e.target.value})}><option value="">Choose lot</option>{lots.map(l=><option key={l.id} value={l.id}>Lot #{l.id} · {l.remaining} {l.unit} · {l.labelDate || 'date unknown'}</option>)}</select></label><label>Removed quantity ({item?.unit || 'stock unit'})<input required type="number" min="0.000001" step="any" value={removal.quantity} onChange={e=>setRemoval({...removal,quantity:e.target.value})}/></label><label>Removal type<select value={removal.kind} onChange={e=>setRemoval({...removal,kind:e.target.value,reason:reasons[e.target.value][0]})}><option value="WASTE">Waste</option><option value="USAGE">Ordinary meal usage</option><option value="COUNT_ADJUSTMENT">Count discrepancy (decrease)</option></select></label><label>Reason<select value={removal.reason} onChange={e=>setRemoval({...removal,reason:e.target.value})}>{reasons[removal.kind].map(r=><option value={r} key={r}>{label(r)}</option>)}</select></label><label className="full">Removal note (optional)<textarea rows="2" maxLength={2000} value={removal.note} onChange={e=>setRemoval({...removal,note:e.target.value})}/></label><div className="full form-footer"><button className="button" disabled={saving||!lots.length}>Record stock removal</button><span className="muted">Date flags never record waste automatically.</span></div></form>}
    {tab==='notes'&&<><form className="panel form-grid" onSubmit={saveNote}><h2 className="full">{note.id?"Edit manager guidance":"Add manager-authored guidance"}</h2><label>Note applies to<select value={note.targetType} onChange={e=>setNote({...note,targetType:e.target.value,targetId:''})}><option value="INGREDIENT">Ingredient</option><option value="RECIPE">Dish</option></select></label><label>Note target<select required value={note.targetId} onChange={e=>setNote({...note,targetId:e.target.value})}><option value="">Choose {note.targetType==='INGREDIENT'?'ingredient':'dish'}</option>{targets.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Note kind<select value={note.kind} onChange={e=>setNote({...note,kind:e.target.value})}><option value="HANDLING">Handling instruction</option><option value="APPROVED_SUBSTITUTION">Manager-approved substitution</option></select></label><label>Author<input required maxLength={120} value={note.actor} onChange={e=>setNote({...note,actor:e.target.value})}/></label><label className="full">Guidance text<textarea required rows="3" maxLength={4000} value={note.text} onChange={e=>setNote({...note,text:e.target.value})}/></label><div className="full"><button className="button" disabled={saving}>{note.id?"Save note changes":"Save manager note"}</button>{note.id&&<button type="button" className="text-button" onClick={()=>setNote({targetType:"INGREDIENT",targetId:"",kind:"HANDLING",text:"",actor:note.actor})}>Cancel note edit</button>}</div></form>{notes.map(n=><article className="panel" key={n.id}><div className="section-title"><h2>{n.targetName}</h2><span className="badge">{label(n.kind)}</span></div><p className="note-text">{n.text}</p><p className="muted small">Last edited by {n.actor} · {n.updatedAt.replace('T',' ')} (kitchen time)</p><button className="text-button" disabled={saving} onClick={()=>{setNote({...n,targetId:String(n.targetId)});window.scrollTo({top:0,behavior:"smooth"})}}>Edit note for {n.targetName}</button></article>)}{!notes.length&&<p className="panel muted">No manager notes yet.</p>}</>}
    {tab==='history'&&<div className="panel"><h2>Recent stock movements</h2><p className="muted">Latest 200 records, newest first. Full movement history remains in MySQL. Waste rows are separate from usage and count discrepancies.</p><div className="table-wrap"><table><thead><tr><th>When</th><th>Ingredient / lot</th><th>Type</th><th>Quantity</th><th>Reason / note</th><th>Recorded by</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{h.createdAt.replace('T',' ')}</td><td>{h.ingredient}<br/>Lot #{h.lotId}</td><td>{label(h.kind)}</td><td>{h.quantity} {h.unit}</td><td>{h.reason?label(h.reason):'Actual receipt'}<div className="muted small">{h.note}</div></td><td>{h.actor}</td></tr>)}</tbody></table></div>{!history.length&&<p className="muted">No movements recorded yet.</p>}</div>}
  </section>
}
