import { useCallback,useEffect,useState } from 'react'

const emptyRecipe=() => ({name:'',ingredients:[{ingredientId:'',quantity:'',unit:'kg'}]})
export default function PlanPanel({items,planDate,api,mutate,saving,reportError,onDraftSaved}) {
  const [recipes,setRecipes]=useState([]),[estimate,setEstimate]=useState(null),[recipeForm,setRecipeForm]=useState(null),[planForm,setPlanForm]=useState(null)
  const [overrides,setOverrides]=useState({}),[requestKey,setRequestKey]=useState(() => crypto.randomUUID())
  const load=useCallback(async () => { const [r,e]=await Promise.all([api.get('/recipes'),api.get(`/estimate?date=${planDate}`)]); setRecipes(r); setEstimate(e); setOverrides({}); setRequestKey(crypto.randomUUID()) },[api,planDate])
  useEffect(() => { if(planDate)load().catch(reportError) },[load,items,planDate,reportError])
  async function change(operation,message) { const result=await mutate(operation,message); if(result)await load(); return result }
  async function saveRecipe(event) { event.preventDefault(); if(await change(() => recipeForm.id?api.put(`/recipes/${recipeForm.id}`,recipeForm):api.post('/recipes',recipeForm),'Dish saved. Requirements recalculated.'))setRecipeForm(null) }
  async function savePlan(event) { event.preventDefault(); if(await change(() => planForm.id?api.put(`/plans/${planForm.id}`,{...planForm,date:planDate}):api.post('/plans',{...planForm,date:planDate}),'Meal plan saved.'))setPlanForm(null) }
  function lineChange(index,key,value) { setRecipeForm({...recipeForm,ingredients:recipeForm.ingredients.map((line,i) => i!==index?line:key==='ingredientId'?{...line,ingredientId:value,unit:items.find(item=>String(item.id)===value)?.unit || 'kg'}:{...line,[key]:value})}) }
  async function saveDraft(event) { event.preventDefault(); const result=await mutate(() => api.post('/drafts',{date:planDate,fingerprint:estimate.fingerprint,overrides:estimate.lines.map(line=>({ingredientId:line.ingredientId,quantity:overrides[line.ingredientId] ?? line.suggested})),requestKey}),'Purchase draft saved. Recorded stock is unchanged.'); if(result){setRequestKey(crypto.randomUUID());onDraftSaved()} }
  return <section>
    <div className="section-heading"><div><p className="eyebrow">FROM MENU TO PURCHASE</p><h1>Tomorrow's plan</h1><p>Plan the dishes. Review your pantry. Decide what to buy.</p></div><div className="actions"><button className="button secondary" disabled={!items.length||saving} onClick={()=>setRecipeForm(emptyRecipe())}>Create dish</button><button className="button" disabled={!recipes.length||saving} onClick={()=>setPlanForm({recipeId:String(recipes[0]?.id || ''),portions:'120'})}>Plan a dish</button></div></div>
    {recipeForm && <form className="panel form-grid" onSubmit={saveRecipe}><h2 className="full">{recipeForm.id?'Edit dish':'Create dish'}</h2><label className="full">Dish name<input required maxLength={120} value={recipeForm.name} onChange={e=>setRecipeForm({...recipeForm,name:e.target.value})}/></label><p className="muted full">Enter the quantity used for one serving. Use each ingredient once.</p>
      {recipeForm.ingredients.map((line,index)=><div className="full recipe-row" key={index}><label>Ingredient {index+1}<select required value={line.ingredientId} onChange={e=>lineChange(index,'ingredientId',e.target.value)}><option value="">Choose ingredient</option>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Per serving {index+1}<input required type="number" min="0.000001" step="any" value={line.quantity} onChange={e=>lineChange(index,'quantity',e.target.value)}/></label><label>Unit {index+1}<select value={line.unit} onChange={e=>lineChange(index,'unit',e.target.value)}>{['kg','g','L','ml','count'].map(u=><option key={u}>{u}</option>)}</select></label><button type="button" className="text-button" aria-label={`Remove ingredient ${index+1}`} disabled={recipeForm.ingredients.length===1} onClick={()=>setRecipeForm({...recipeForm,ingredients:recipeForm.ingredients.filter((_,i)=>i!==index)})}>×</button></div>)}
      <div className="full"><button type="button" className="text-button" disabled={recipeForm.ingredients.length>=50} onClick={()=>setRecipeForm({...recipeForm,ingredients:[...recipeForm.ingredients,{ingredientId:'',quantity:'',unit:'kg'}]})}>+ Add recipe ingredient</button></div><div className="full form-footer"><button className="button" disabled={saving}>Save dish</button><button type="button" className="text-button" onClick={()=>setRecipeForm(null)}>Cancel</button></div>
    </form>}
    {planForm && <form className="panel form-grid" onSubmit={savePlan}><h2 className="full">{planForm.id?'Edit planned dish':'Plan a dish'} · {planDate}</h2><label>Dish<select required value={planForm.recipeId} onChange={e=>setPlanForm({...planForm,recipeId:e.target.value})}>{recipes.map(recipe=><option key={recipe.id} value={recipe.id}>{recipe.name}</option>)}</select></label><label>Portions / covers<input required type="number" min="1" max="100000" step="1" value={planForm.portions} onChange={e=>setPlanForm({...planForm,portions:e.target.value})}/></label><div className="full form-footer"><button className="button" disabled={saving}>Save planned dish</button><button type="button" className="text-button" onClick={()=>setPlanForm(null)}>Cancel</button></div></form>}
    <div className="two-column"><div className="panel"><div className="section-title"><h2>What are we cooking?</h2><span className="plan-date">{planDate}</span></div>{!estimate?.plans.length&&<p className="muted">No dishes planned for this date. Choose a dish and its portions.</p>}{estimate?.plans.map(plan=><div className="compact-row" key={plan.id}><div><strong>{plan.name}</strong><small>{plan.portions} portions</small></div><button className="text-button push" disabled={saving} onClick={()=>setPlanForm({...plan,recipeId:String(plan.recipeId),portions:String(plan.portions)})}>Edit {plan.name}</button><button className="text-button" disabled={saving} onClick={()=>change(()=>api.remove(`/plans/${plan.id}`),'Planned dish removed.').catch(reportError)}>Remove {plan.name}</button></div>)}</div>
      <div className="panel"><h2>Your dishes</h2>{!recipes.length&&<p className="muted">Create your first dish after adding ingredients in Stock & dates.</p>}{recipes.map(recipe=><div className="compact-row" key={recipe.id}><div><strong>{recipe.name}</strong><small>{recipe.ingredients.length} ingredients per serving</small></div><button className="text-button push" disabled={saving} onClick={()=>setRecipeForm({...recipe,ingredients:recipe.ingredients.map(l=>({...l,ingredientId:String(l.ingredientId)}))})}>Edit recipe {recipe.name}</button><button className="text-button" disabled={saving} onClick={()=>change(()=>api.remove(`/recipes/${recipe.id}`),'Dish archived.').catch(reportError)}>Archive {recipe.name}</button></div>)}</div></div>
    {estimate?.lines.length>0&&<><div className="panel"><h2>What do we have, and what needs review?</h2><p className="muted">Entered dates before {planDate} are excluded from this estimate. Unknown dates stay in recorded usable stock and require manager review. No lot is automatically marked as waste.</p><div className="table-wrap"><table><thead><tr><th>Ingredient</th><th>Required</th><th>On hand</th><th>Date excluded</th><th>Usable</th><th>Buffer</th><th>Buy</th></tr></thead><tbody>{estimate.lines.map(line=><tr key={line.ingredientId} data-testid={`estimate-${line.name}`}><td><strong>{line.name}</strong><div className="muted small">All quantities in {line.unit}</div>{line.reviewLots.length>0&&<div className="badge review">{line.reviewLots.length} lot(s) need review</div>}</td>{['required','onHand','excluded','usable','buffer','suggested'].map(key=><td key={key} data-testid={key}>{line[key]}</td>)}</tr>)}</tbody></table></div></div>
      {estimate.lines.map(line=><div className="panel" key={line.ingredientId}><div className="section-title"><h2>{line.name} · arithmetic</h2><span className="badge">{line.unit}</span></div>{line.breakdown.map((b,i)=><p className="arithmetic" key={i}>{b.dish}: {b.portions} × {b.perServing} {line.unit} = {b.required} {line.unit}</p>)}<p className="arithmetic">max(0, {line.required} required + {line.buffer} buffer − {line.usable} usable) = {line.rawSuggestion} {line.unit}{Number(line.increment)>0?`; rounded up to ${line.increment} ${line.unit} steps = ${line.suggested} ${line.unit}`:''}</p>{line.reviewLots.map(l=><p className="muted small" key={l.lotId}>Lot #{l.lotId}: {l.quantity} {line.unit} · {l.labelDate || 'Date unknown'} · {l.excluded?'excluded pending review':'manager review needed'}</p>)}<Settings key={`${estimate.fingerprint}-${line.ingredientId}`} line={line} date={planDate} save={body=>change(()=>api.put(`/planning-settings/${line.ingredientId}`,body),'Planning settings saved.')} saving={saving}/></div>)}
      <form className="panel accent-panel" onSubmit={saveDraft}><h2>What should we order?</h2><p className="muted">Review and edit the quantities below. This saves a draft for your decision; it does not place an order or add stock.</p><div className="table-wrap"><table><thead><tr><th>Ingredient</th><th>Suggested</th><th>Your draft quantity</th></tr></thead><tbody>{estimate.lines.map(line=><tr key={line.ingredientId}><td>{line.name} ({line.unit})</td><td>{line.suggested}</td><td><input aria-label={`Draft quantity ${line.name}`} required type="number" min="0" step="any" value={overrides[line.ingredientId] ?? line.suggested} onChange={e=>setOverrides({...overrides,[line.ingredientId]:e.target.value})}/></td></tr>)}</tbody></table></div><button className="button" disabled={saving}>Save purchase draft</button></form></>}
  </section>
}
function Settings({line,date,save,saving}) { const [buffer,setBuffer]=useState(line.buffer),[increment,setIncrement]=useState(line.increment); return <form className="form-grid" onSubmit={e=>{e.preventDefault();save({date,buffer,increment,unit:line.unit})}}><label>Buffer for {line.name}<input required type="number" min="0" step="any" value={buffer} onChange={e=>setBuffer(e.target.value)}/></label><label>Purchase increment for {line.name}<input required type="number" min="0" step="any" value={increment} onChange={e=>setIncrement(e.target.value)}/></label><div className="full form-footer"><button className="button secondary" disabled={saving}>Apply settings for {line.name}</button><span className="muted">Buffer is extra stock you choose for this date. Zero adds none. Increment is a purchase step; zero keeps the exact suggestion.</span></div></form> }
