import { useEffect,useState } from 'react'
import { dateTypes } from './api'
import { useLanguage } from './language'

function compatibleUnits(unit) { return ['kg','g'].includes(unit) ? ['kg','g'] : ['L','ml','liters','litres'].includes(unit) ? ['L','ml'] : ['count'] }
function dateTypeLabel(type,language){if(language==='en')return dateTypes[type];return ({USE_BY:'उपयोग की अंतिम तारीख',BEST_BEFORE:'इस तारीख से पहले बेहतर',SUPPLIER_LABEL:'आपूर्तिकर्ता का लेबल',UNKNOWN:'तारीख का प्रकार अज्ञात'})[type]||dateTypes[type]}
export default function StockPanel({items, today, planDate, mutate, api, saving = false,preset,hideStock=false,onRecorded}) {
  const { t, language } = useLanguage()
  const [form,setForm] = useState(null),[lotsOpen,setLotsOpen]=useState({})
  const [receipt,setReceipt] = useState({ingredientId:'',quantity:'',unit:'kg',unitCost:'',supplier:'',receivedDate:today,labelDate:'',dateType:'UNKNOWN'})
  const [requestKey,setRequestKey] = useState(() => crypto.randomUUID()),[newItem,setNewItem] = useState({name:'',unit:'kg'})
  useEffect(()=>{ if(preset){setReceipt({ingredientId:String(preset.ingredientId),quantity:preset.quantity,unit:preset.unit,unitCost:'',supplier:'',receivedDate:today,labelDate:'',dateType:'UNKNOWN',draftLineId:preset.id});setRequestKey(crypto.randomUUID());setForm('receipt')} },[preset,today])
  function openReceipt() { const first=items[0];setReceipt(previous => ({...previous,ingredientId:String(first?.id || ''),unit:first?.unit || 'kg'}));setForm(form==='receipt'?null:'receipt') }
  async function submitReceipt(event) { event.preventDefault();if(await mutate(() => api.post('/receipts',{...receipt,requestKey}),{key:'support.receiptSuccess'})) { setRequestKey(crypto.randomUUID());setReceipt(previous => ({...previous,quantity:'',unitCost:''}));setForm(null);onRecorded?.() } }
  async function create(event) { event.preventDefault();if(await mutate(() => api.post('/ingredients',newItem),{key:'support.ingredientSuccess'})) { setNewItem({name:'',unit:'kg'});setForm(null) } }
  const selected=items.find(item => String(item.id)===receipt.ingredientId),update=(key,value) => setReceipt({...receipt,[key]:value})
  return <section>
    {!hideStock&&<div className="section-heading"><div><p className="eyebrow">{t('support.stockEyebrow')}</p><h1>{t('support.stockTitle')}</h1><p>{t('support.stockIntro')}</p></div><div className="actions"><button className="button secondary" disabled={saving} onClick={() => setForm(form==='ingredient'?null:'ingredient')}>{t('support.addIngredient')}</button><button className="button" disabled={!items.length||saving} onClick={openReceipt}>{t('support.receive')}</button></div></div>}
    {form==='ingredient' && <form className="panel form-grid" onSubmit={create}><fieldset disabled={saving} className="form-grid-lock"><h2 className="full">{t('support.newIngredient')}</h2><label>{t('support.ingredientName')}<input required maxLength={120} value={newItem.name} onChange={event => setNewItem({...newItem,name:event.target.value})}/></label><label>{t('support.stockUnit')}<select value={newItem.unit} onChange={event => setNewItem({...newItem,unit:event.target.value})}>{['kg','g','L','ml','count'].map(unit => <option key={unit}>{unit}</option>)}</select></label><div className="full form-footer"><button className="button" disabled={saving}>{t('support.createIngredient')}</button><button type="button" className="text-button" onClick={() => setForm(null)}>{t('support.cancel')}</button></div></fieldset></form>}
    {form==='receipt' && <form className="panel form-grid" onSubmit={submitReceipt}><fieldset disabled={saving} className="form-grid-lock"><div className="full"><h2>{t('support.receiptTitle')}</h2><p className="muted">{t('support.receiptIntro')}</p></div>
      <label>{t('support.ingredient')}<select required disabled={Boolean(receipt.draftLineId)} value={receipt.ingredientId} onChange={event => { const item=items.find(row => String(row.id)===event.target.value); setReceipt({...receipt,ingredientId:event.target.value,unit:item.unit}) }}>{items.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label>{t('support.receivedQuantity')}<input required type="number" min="0.000001" step="any" value={receipt.quantity} onChange={event => update('quantity',event.target.value)}/></label><label>{t('support.receivedUnit')}<select value={receipt.unit} onChange={event => update('unit',event.target.value)}>{compatibleUnits(selected?.unit || 'kg').map(unit => <option key={unit}>{unit}</option>)}</select></label>
      <label>{t('support.unitCost')}<input required type="number" min="0" step="0.0001" value={receipt.unitCost} onChange={event => update('unitCost',event.target.value)}/></label><label>{t('support.supplier')}<input maxLength={160} value={receipt.supplier} onChange={event => update('supplier',event.target.value)}/></label><label>{t('support.receivedDate')}<input required type="date" max={today} value={receipt.receivedDate} onChange={event => update('receivedDate',event.target.value)}/></label>
      <label>{t('support.labelDate')}<input type="date" value={receipt.labelDate} onChange={event => setReceipt({...receipt,labelDate:event.target.value,dateType:event.target.value?'USE_BY':'UNKNOWN'})}/></label><label>{t('support.dateType')}<select value={receipt.dateType} onChange={event => update('dateType',event.target.value)}>{Object.keys(dateTypes).map(key => <option key={key} value={key}>{dateTypeLabel(key,language)}</option>)}</select></label>
      <div className="full form-footer"><button className="button" disabled={saving}>{t('support.recordReceipt')}</button><button type="button" className="text-button" onClick={() => setForm(null)}>{t('support.cancel')}</button></div></fieldset></form>}
    {!hideStock&&<><p className="notice">{t('support.notice')}</p>{!items.length&&<div className="empty panel"><h2>{t('support.startIngredient')}</h2><p>{t('support.startIngredientBody')}</p></div>}
      <div className="stock-grid">{items.map(item=>{const dated=item.lots.filter(lot=>lot.labelDate),unknown=item.lots.length-dated.length,review=item.lots.filter(lot=>lot.labelDate&&(lot.labelDate<(planDate||today))).length;return <article className="panel stock-card" key={item.id}><div className="stock-title"><h2>{item.name}</h2><span className="quantity">{item.onHand} <small>{item.unit}</small></span></div><p className="muted small">{t('support.stockTotal')}</p>{item.conversionError&&<p className="error">{item.conversionError}</p>}<p className="muted small">{dated.length} {language==='en'?'dated lots':'तारीख वाले lots'} · {unknown} {language==='en'?'unknown-date lots':'अज्ञात तारीख वाले lots'} · {review} {language==='en'?'for date review':'तारीख समीक्षा के लिए'}</p>{review>0&&<p className="badge review">{t('support.reviewCount',{count:review})}</p>}{!item.lots.length&&<p className="muted">{t('support.noReceipts')}</p>}
        {Boolean(item.lots.length)&&<><button className="text-button" type="button" aria-expanded={Boolean(lotsOpen[item.id])} onClick={()=>setLotsOpen(current=>({...current,[item.id]:!current[item.id]}))}>{t(lotsOpen[item.id]?'support.closeLots':'support.closedLots')}</button>{lotsOpen[item.id]&&<div className="lot-list">{item.lots.map(lot=>{const needsReview=lot.labelDate&&lot.labelDate<(planDate||today);return <div className="lot" key={lot.id}><div><strong>{t('support.lot',{id:lot.id,quantity:lot.remaining,unit:lot.unit})}</strong><span className={`badge ${needsReview?'review':!lot.labelDate?'unknown':''}`}>{!lot.labelDate?t('support.unknown'):needsReview?t('support.reviewDate'):t('support.dateRecorded')}</span></div><p>{t('support.received',{date:lot.receivedDate})}{lot.supplier?` · ${lot.supplier}`:''}</p><p>{lot.labelDate?`${dateTypeLabel(lot.dateType,language)}: ${lot.labelDate}`:t('support.noLabel')}{lot.openingBalance?t('support.opening'):''}</p><p className="muted small">{t('support.costAtReceipt',{cost:lot.unitCost,unit:lot.inputUnit})}</p></div>})}</div>}</>}
      </article>})}</div></>}
  </section>
}
