import { test,expect } from '@playwright/test'
import path from 'node:path'

test('manager completes receipts, planning, override, partial arrival, spoilage and guidance',async({page},testInfo)=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button',{name:'Reset fictional kitchen',exact:true}).click()
  await page.getByLabel('Starting point').selectOption('walkthrough')
  await page.getByLabel('Type RESET FICTIONAL KITCHEN').fill('RESET FICTIONAL KITCHEN')
  await page.getByRole('button',{name:'Reseed sample data'}).click()
  await expect(page.getByRole('status')).toContainText('Fictional kitchen reset')
  const tomorrow=await page.getByLabel('Planning date').inputValue()
  const dates=await page.request.get('/api/prep/demo');const {sampleDate}=await dates.json();expect(tomorrow).toBe(sampleDate)
  await page.getByRole('button',{name:'Stock & dates',exact:true}).click()
  const dateOffset=(value,offset)=>{const d=new Date(`${value}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)}
  async function receipt(qty,label){
    await page.getByRole('button',{name:'Receive stock',exact:true}).click()
    await page.getByRole('combobox',{name:'Ingredient',exact:true}).selectOption({label:'Tomatoes'})
    await page.getByLabel('Received quantity',{exact:true}).fill(qty)
    await page.getByLabel('Cost per received unit (₹)',{exact:true}).fill('30')
    await page.getByLabel('Supplier (optional)',{exact:true}).fill('Fictional campus supplier')
    await page.getByLabel('Label date (optional)',{exact:true}).fill(label)
    await page.getByRole('combobox',{name:'Date type',exact:true}).selectOption('BEST_BEFORE')
    await page.getByRole('button',{name:'Record receipt',exact:true}).click()
    await expect(page.getByRole('status')).toContainText('Receipt recorded')
  }
  await receipt('7',dateOffset(tomorrow,3));await receipt('3',dateOffset(tomorrow,-2))
  const tomatoCard=page.locator('article').filter({has:page.getByRole('heading',{name:'Tomatoes',exact:true})})
  await expect(tomatoCard.locator('.quantity')).toHaveText('10 kg');await expect(tomatoCard.getByText('Review entered date')).toBeVisible()
  await page.screenshot({path:path.join(testInfo.outputDir,'05-stock.png'),fullPage:true})
  await page.reload();await page.getByRole('button',{name:'Stock & dates',exact:true}).click();await expect(tomatoCard.locator('.quantity')).toHaveText('10 kg')
  await page.getByRole('button',{name:"Tomorrow's plan",exact:true}).click()
  for(const dish of ['Vegetable pulao','Paneer curry']){
    await page.getByRole('button',{name:'Plan a dish',exact:true}).click();await page.getByRole('combobox',{name:'Dish',exact:true}).selectOption({label:dish});await page.getByLabel('Portions / covers').fill('120');await page.getByRole('button',{name:'Save planned dish',exact:true}).click();await expect(page.getByRole('status')).toContainText('Meal plan saved')
  }
  const row=page.getByTestId('estimate-Tomatoes')
  for(const [key,value] of Object.entries({required:'18',onHand:'10',excluded:'3',usable:'7',buffer:'0',suggested:'11'}))await expect(row.getByTestId(key)).toHaveText(value)
  await page.screenshot({path:path.join(testInfo.outputDir,'01-plan.png'),fullPage:true})
  await page.getByLabel('Draft quantity Tomatoes',{exact:true}).fill('12');await page.getByRole('button',{name:'Save purchase draft',exact:true}).click();await expect(page.getByRole('heading',{name:'Purchase drafts',exact:true})).toBeVisible()
  await expect(page.getByTestId('outstanding-Tomatoes')).toHaveText('12')
  await page.screenshot({path:path.join(testInfo.outputDir,'04-draft.png'),fullPage:true})
  await page.reload();await page.getByRole('button',{name:'Purchase drafts',exact:true}).click();await expect(page.getByTestId('outstanding-Tomatoes')).toHaveText('12')
  await page.getByRole('button',{name:/Receive Tomatoes from draft/}).click();await page.getByLabel('Received quantity',{exact:true}).fill('11');await page.getByLabel('Cost per received unit (₹)',{exact:true}).fill('30');await page.getByLabel('Label date (optional)',{exact:true}).fill(dateOffset(tomorrow,3));await page.getByRole('button',{name:'Record receipt',exact:true}).click();await expect(page.getByTestId('outstanding-Tomatoes')).toHaveText('1')
  await page.getByRole('button',{name:"Tomorrow's plan",exact:true}).click();await expect(row.getByTestId('usable')).toHaveText('18');await expect(row.getByTestId('suggested')).toHaveText('0')
  await page.getByRole('button',{name:'Waste & notes',exact:true}).click();await page.getByLabel('Removal ingredient').selectOption({label:'Tomatoes'});const options=await page.getByLabel('Selected lot').locator('option').allTextContents();const eligible=options.find(x=>x.includes('7 kg'));await page.getByLabel('Selected lot').selectOption({label:eligible});await page.getByLabel('Removed quantity (kg)',{exact:true}).fill('3');await page.getByRole('combobox',{name:'Reason',exact:true}).selectOption('SPOILED');await page.getByLabel('Removal note (optional)').fill('Fictional walkthrough: damaged condition observed');await page.getByRole('button',{name:'Record stock removal'}).click();await expect(page.getByRole('status')).toContainText('Stock removal recorded once')
  await page.getByRole('button',{name:"Tomorrow's plan",exact:true}).click();await expect(row.getByTestId('onHand')).toHaveText('18');await expect(row.getByTestId('usable')).toHaveText('15');await expect(row.getByTestId('suggested')).toHaveText('3')
  await page.getByRole('button',{name:'Waste & notes',exact:true}).click();await page.getByRole('button',{name:'Manager notes',exact:true}).click();await expect(page.getByText(/Fictional manager note: keep lots separate/)).toBeVisible()
  await page.getByRole('button',{name:'Edit note for Tomatoes',exact:true}).click();await page.getByLabel('Author',{exact:true}).fill('Anita Rao (sample kitchen lead)');await page.getByRole('textbox',{name:'Guidance text',exact:true}).fill('Fictional manager note: keep lots separate; reviewed today by the sample kitchen lead.');await page.getByRole('button',{name:'Save note changes',exact:true}).click();await expect(page.getByRole('status')).toContainText('Manager note saved')
  await page.reload();await page.getByRole('button',{name:'Waste & notes',exact:true}).click();await page.getByRole('button',{name:'Manager notes',exact:true}).click();await expect(page.getByText('Fictional manager note: keep lots separate; reviewed today by the sample kitchen lead.',{exact:true})).toBeVisible();await expect(page.getByText(/Last edited by Anita Rao \(sample kitchen lead\)/)).toBeVisible();await page.screenshot({path:path.join(testInfo.outputDir,'02-guidance.png'),fullPage:true});await page.getByRole('button',{name:'Movement history',exact:true}).click();await expect(page.getByRole('cell',{name:'Spoiled',exact:false})).toBeVisible();await page.screenshot({path:path.join(testInfo.outputDir,'03-history.png'),fullPage:true})
  expect(errors).toEqual([])
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})

test('manager creates and edits a recipe, changes covers and purchase settings, and removes a plan',async({page})=>{
  await page.goto('/');await page.getByRole('button',{name:'Reset fictional kitchen',exact:true}).click();await page.getByLabel('Type RESET FICTIONAL KITCHEN').fill('RESET FICTIONAL KITCHEN');await page.getByRole('button',{name:'Reseed sample data'}).click();await expect(page.getByRole('status')).toContainText('Fictional kitchen reset')
  await page.getByRole('button',{name:'Create dish',exact:true}).click();await page.getByLabel('Dish name',{exact:true}).fill('Browser test dish');await page.getByRole('combobox',{name:'Ingredient 1',exact:true}).selectOption({label:'Tomatoes'});await page.getByLabel('Per serving 1',{exact:true}).fill('0.01');await page.getByRole('button',{name:'Save dish',exact:true}).click();await expect(page.getByRole('status')).toContainText('Dish saved')
  await page.getByRole('button',{name:'Plan a dish',exact:true}).click();await page.getByRole('combobox',{name:'Dish',exact:true}).selectOption({label:'Browser test dish'});await page.getByLabel('Portions / covers').fill('100');await page.getByRole('button',{name:'Save planned dish',exact:true}).click();const row=page.getByTestId('estimate-Tomatoes');await expect(row.getByTestId('required')).toHaveText('19')
  await page.getByRole('button',{name:'Edit Browser test dish',exact:true}).click();await page.getByLabel('Portions / covers').fill('50');await page.getByRole('button',{name:'Save planned dish',exact:true}).click();await expect(row.getByTestId('required')).toHaveText('18.5')
  await page.getByRole('button',{name:'Edit recipe Browser test dish',exact:true}).click();await page.getByLabel('Per serving 1',{exact:true}).fill('0.02');await page.getByRole('button',{name:'Save dish',exact:true}).click();await expect(row.getByTestId('required')).toHaveText('19')
  await page.getByLabel('Buffer for Tomatoes',{exact:true}).fill('0.1');await page.getByLabel('Purchase increment for Tomatoes',{exact:true}).fill('5');await page.getByRole('button',{name:'Apply settings for Tomatoes',exact:true}).click();await expect(row.getByTestId('buffer')).toHaveText('0.1');await expect(row.getByTestId('suggested')).toHaveText('15')
  await page.getByRole('button',{name:'Remove Browser test dish',exact:true}).click();await expect(row.getByTestId('required')).toHaveText('18');await page.getByRole('button',{name:'Archive Browser test dish',exact:true}).click();await expect(page.getByRole('button',{name:'Edit recipe Browser test dish',exact:true})).toHaveCount(0)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})
